version: "2"
services:
  pixart_dev_api:
    build:
      context: ../
      dockerfile: docker/Dockerfile.dev
      args:
        port: ${PORT}
    env_file:
      - ../.env
    restart: always
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - db_dev
    links:
      - db_dev
    environment:
      DATABASE_URL: postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}
  db_dev:
    image: postgres
    env_file:
      - ../.env
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ../tables.sql:/docker-entrypoint-initdb.d/init.sql
