version: "2"
services:
  db_dev:
    image: postgres
    env_file:
      - ../.env
    restart: always
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ../tables.sql:/docker-entrypoint-initdb.d/init.sql
