FROM docker_pixart_api
COPY tests tests
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.2.1/wait /wait
RUN chmod +x /wait
ENV NODE_ENV test
RUN npm install && npm install -g mocha
ARG port=80
CMD /wait && tsc && mocha tests/test.js --reporter spec --timeout 10000 --exit
