FROM node:latest
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.2.1/wait /wait
RUN chmod +x /wait
WORKDIR /home/nodejs/app
ENV NODE_ENV dev
COPY package*.json ./
RUN npm install && npm install -g typescript
ARG port=3001
EXPOSE $port
COPY . ./
COPY dev.env /.env
CMD /wait && npm run start
